-- Tabla de gastos recurrentes (suscripciones, pagos fijos mensuales)

create table public.gastos_recurrentes (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  descripcion text not null,
  monto decimal not null check (monto > 0),
  categoria text not null,
  dia_mes smallint not null check (dia_mes >= 1 and dia_mes <= 31),
  ultimo_registro timestamptz,
  cuenta_id uuid references public.cuentas (id) on delete set null,
  created_at timestamptz default timezone('utc', now()) not null
);

alter table public.gastos_recurrentes enable row level security;

create policy "Usuarios pueden ver sus gastos recurrentes"
on public.gastos_recurrentes for select
using (auth.uid() = user_id);

create policy "Usuarios pueden insertar sus gastos recurrentes"
on public.gastos_recurrentes for insert
with check (auth.uid() = user_id);

create policy "Usuarios pueden actualizar sus gastos recurrentes"
on public.gastos_recurrentes for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Usuarios pueden eliminar sus gastos recurrentes"
on public.gastos_recurrentes for delete
using (auth.uid() = user_id);

create trigger gastos_recurrentes_set_user_id
before insert on public.gastos_recurrentes
for each row execute function public.set_auth_user_id();

create index gastos_recurrentes_user_id_idx on public.gastos_recurrentes (user_id);
create index gastos_recurrentes_cuenta_id_idx on public.gastos_recurrentes (cuenta_id);
