-- Ejecutar después de drop_gastos.sql (o en proyecto nuevo sin tabla previa)

create table public.gastos (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  monto decimal not null check (monto > 0),
  categoria text not null,
  fecha timestamptz default timezone('utc', now()) not null,
  descripcion text,
  created_at timestamptz default timezone('utc', now()) not null
);

alter table public.gastos enable row level security;

create policy "Usuarios pueden ver sus propios gastos"
on public.gastos for select
using (auth.uid() = user_id);

create policy "Usuarios pueden insertar sus propios gastos"
on public.gastos for insert
with check (auth.uid() = user_id);

create policy "Usuarios pueden actualizar sus propios gastos"
on public.gastos for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Usuarios pueden eliminar sus propios gastos"
on public.gastos for delete
using (auth.uid() = user_id);

create or replace function public.set_gasto_user_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.user_id := auth.uid();
  return new;
end;
$$;

create trigger gastos_set_user_id
before insert on public.gastos
for each row execute function public.set_gasto_user_id();

create index gastos_user_id_idx on public.gastos (user_id);
create index gastos_fecha_idx on public.gastos (fecha desc);
create index gastos_user_id_fecha_idx on public.gastos (user_id, fecha desc);
