-- Registro de ingresos extra a cuentas (bonos, ventas, etc.)

create table if not exists public.ingresos_cuenta (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  cuenta_id uuid not null references public.cuentas(id) on delete cascade,
  monto decimal not null check (monto > 0),
  descripcion text not null,
  fecha timestamptz default timezone('utc', now()) not null,
  created_at timestamptz default timezone('utc', now()) not null
);

alter table public.ingresos_cuenta enable row level security;

create policy "Usuarios pueden ver sus propios ingresos"
on public.ingresos_cuenta for select
using (auth.uid() = user_id);

create policy "Usuarios pueden insertar sus propios ingresos"
on public.ingresos_cuenta for insert
with check (auth.uid() = user_id);

create or replace function public.set_ingreso_cuenta_user_id()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  new.user_id := auth.uid();
  return new;
end;
$$;

drop trigger if exists ingresos_cuenta_set_user_id on public.ingresos_cuenta;
create trigger ingresos_cuenta_set_user_id
before insert on public.ingresos_cuenta
for each row execute function public.set_ingreso_cuenta_user_id();

create index if not exists ingresos_cuenta_user_id_idx on public.ingresos_cuenta (user_id);
create index if not exists ingresos_cuenta_cuenta_id_idx on public.ingresos_cuenta (cuenta_id);
create index if not exists ingresos_cuenta_fecha_idx on public.ingresos_cuenta (fecha desc);
