-- Metas de ahorro por usuario

create table public.metas_ahorro (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users on delete cascade,
  nombre text not null,
  monto_objetivo decimal not null check (monto_objetivo > 0),
  monto_actual decimal not null default 0 check (monto_actual >= 0),
  fecha_limite date,
  created_at timestamptz default timezone('utc', now()) not null
);

alter table public.metas_ahorro enable row level security;

create policy "Usuarios pueden ver sus metas de ahorro"
on public.metas_ahorro for select
using (auth.uid() = user_id);

create policy "Usuarios pueden insertar sus metas de ahorro"
on public.metas_ahorro for insert
with check (auth.uid() = user_id);

create policy "Usuarios pueden actualizar sus metas de ahorro"
on public.metas_ahorro for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Usuarios pueden eliminar sus metas de ahorro"
on public.metas_ahorro for delete
using (auth.uid() = user_id);

create trigger metas_ahorro_set_user_id
before insert on public.metas_ahorro
for each row execute function public.set_gasto_user_id();

create index metas_ahorro_user_id_idx on public.metas_ahorro (user_id);
